# /* prometheus chart config */
prometheus:
  server:
    persistentVolume:
      enabled: true
    service:
      type: NodePort
      nodePort: 30090
  extraScrapeConfigs: ""

# /* grafana chart config */
grafana:
  service:
    type: NodePort
    nodePort: 30080
  persistence:
    type: pvc
    enabled: true
  adminUser: admin
  adminPassword: admin

# /* tempo chart config */
tempo:
  tempo:
    retention: 1h
    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces
        wal:
          path: /var/tempo/wal
    receivers:
      jaeger:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14250
          thrift_binary:
            endpoint: 0.0.0.0:6832
          thrift_compact:
            endpoint: 0.0.0.0:6831
          thrift_http:
            endpoint: 0.0.0.0:14268
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
  
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
